### ISSUE TITLE
Dead code may not be working as intended

### ISSUE THREAD

**Issue by Lonami** [ultrafunkamsterdam/googletranslate#1]
Lines 266 to 267 here:
https://github.com/ultrafunkamsterdam/googletranslate/blob/bd3f4d0a1386ffa634c8ebbebb3603279f3ece99/googletranslate/__init__.py#L264-L267

Seem to do nothing. Perhaps the following was intended?:
```python
        if self._tkk:
            now: str = str(int(time.time() / 3600))
            if self._tkk.split(".")[0] == now:
                self._ttk = None
```

So that it can be re-fetched every hour.

**Comment by ultrafunkamsterdam** [comment]
Hmm, no i think my intention was to have the else block indented, so when not matching, request a new one.   I will test that and report back. thanks for your comment

**Comment by ultrafunkamsterdam** [comment]
Thanks. updated code with a more elegant solution.
[89d89b13465b20f2e4538387bb0205781e05d766](https://github.com/ultrafunkamsterdam/googletranslate/commit/89d89b13465b20f2e4538387bb0205781e05d766)
