### ISSUE TITLE
[question] the logic behind `_calc_token`

### ISSUE THREAD

**Issue by WaffleLapkin** [ultrafunkamsterdam/googletranslate#5]
Can you explain the logic behind [`_calc_token`][ct]? Without any comments, with one-letter-variables and with a lot of computations/magic constants it's very hard to read/understand.

[ct]: https://github.com/ultrafunkamsterdam/googletranslate/blob/master/googletranslate/__init__.py#L264-L328

**Comment by Lonami** [comment]
It's (probably) ported from Google's minified JavaScript code, with no need to understand it. The only thing to know is that this is how the token is calculated, and that will make it work.

**Comment by ultrafunkamsterdam** [comment]
the first part of the tkk is the epoch in hours. also a tkk can , once created live for days/weeks even reported. however renewing it every hour seemed the safer way. i got it from  https://translate.google.com/translate/releases/twsfe_w_20160620_RC00/r/js/desktop_module_main.js ... good luck

**Comment by Lonami** [comment]
You can think of "tkk" as a "token key" that needs to be refreshed and is used to generate per-text "tk" tokens.

**Comment by WaffleLapkin** [comment]
Thanks
